### ISSUE TITLE
Remove deprecated @jsx pragma from draggable_test.jsx

### ISSUE THREAD

**Issue by havardge** [mikepb/react-draggable#12]
Hi,

This project is used by [material-ui](https://github.com/callemall/material-ui/blob/master/package.json#L33). Is it possible to remove the `@jsx React.DOM` from [draggable_test.jsx](https://github.com/mikepb/react-draggable/blob/master/test/draggable_test.jsx#L1) and update the [NPM module](https://www.npmjs.com/package/react-draggable2)?

I'm asking since this `@jsx React.DOM` is breaking my grunt build

**Comment by mikepb** [comment]
Thanks @havardge !
